language: ruby
rvm:
  - 2.1.0
bundler_args: --without production development
services:
  - postgresql: 9.3
before_script:
  - psql -c 'CREATE DATABASE flesh_test;' -U postgres
  - bundle exec rake db:setup --trace
